### ISSUE TITLE
All logins reported as suspicious - underlying DataLoader.php bug

### ISSUE THREAD

**Issue by billgertz** [nextcloud/suspicious_login#862] opened 2024-03-18 13:33 UTC
Any login attempt results in a _nextcloud.log_ entry with the following details:

```
InvalidArgumentException
Datasets must have the same number of columns, 48 expected, but 16 given.
/usr/local/lib/owncloud/apps/suspicious_login/lib/Service/DataLoader.php
line 131
Rubix\ML\Datasets\Labeled->merge()
/usr/local/lib/owncloud/apps/suspicious_login/lib/Service/TrainService.php
line 72
OCA\SuspiciousLogin\Service\DataLoader->generateRandomShuffledData()
/usr/local/lib/owncloud/apps/suspicious_login/lib/BackgroundJob/TrainJobIpV4.php
line 70
OCA\SuspiciousLogin\Service\TrainService->train()
/usr/local/lib/owncloud/lib/public/BackgroundJob/Job.php
line 81
OCA\SuspiciousLogin\BackgroundJob\TrainJobIpV4->run()
/usr/local/lib/owncloud/lib/public/BackgroundJob/TimedJob.php
line 102
OCP\BackgroundJob\Job->start()
/usr/local/lib/owncloud/lib/public/BackgroundJob/TimedJob.php
line 92
OCP\BackgroundJob\TimedJob->start()
/usr/local/lib/owncloud/cron.php
line 152
OCP\BackgroundJob\TimedJob->execute()
```

This probably related to issue https://github.com/nextcloud/suspicious_login/issues/860

How to replicate:

1. Login into nextcloud as any user
2. Login into nextcloud as Admin
3. Goto Adimistrative Settings > Administration > Logging
4. Find the suspicious_login entry and click on the hamburger ( '...')
5. Select Show details

Should see something like the attached screenshot.
![Screenshot 2024-03-18 at 14 31 30](https://github.com/nextcloud/suspicious_login/assets/3613249/1840e17b-bbe3-4023-97e4-bb55194459e0)

**Comment by joshtrichards** [comment] 2024-04-01 18:27
Duplicate of #860

**Closed by joshtrichards** 2024-04-01 18:27 UTC
