### ISSUE TITLE
Can not start training

### ISSUE THREAD

**Issue by Padi100** [nextcloud/suspicious_login#866] opened 2024-03-30 10:03 UTC
If I want to start a train run it fails with the following error:

```
Using ipv4 strategy
In Labeled.php line 364:
Datasets must have the same number of columns, 48 expected, but 16 given.
```

In verbose-mode I get:
```
Using ipv4 strategy
In Labeled.php line 364:
  [Rubix\ML\Exceptions\InvalidArgumentException]
  Datasets must have the same number of columns, 48 expected, but 16 given.
Exception trace:
  at /var/www/nextcloud/apps/suspicious_login/vendor/rubix/ml/src/Datasets/Labeled.php:364
 Rubix\ML\Datasets\Labeled->merge() at /var/www/nextcloud/apps/suspicious_login/lib/Service/DataLoader.php:131
 OCA\SuspiciousLogin\Service\DataLoader->generateRandomShuffledData() at /var/www/nextcloud/apps/suspicious_login/lib/Command/Train.php:173
 OCA\SuspiciousLogin\Command\Train->execute() at /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /var/www/nextcloud/3rdparty/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at /var/www/nextcloud/3rdparty/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /var/www/nextcloud/3rdparty/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /var/www/nextcloud/lib/private/Console/Application.php:213
 OC\Console\Application->run() at /var/www/nextcloud/console.php:100
 require_once() at /var/www/nextcloud/occ:11
```

In Nextcloud it shows that there was a run back 9 months ago.
![2024-03-30 11_00_29-Security - Administration settings - Nextcloud](https://github.com/nextcloud/suspicious_login/assets/146137354/79bcb704-97f9-4e08-96a7-4df6e4a43be9)

Is it possible to completely reset the suspicious_login app?

**Comment by joshtrichards** [comment] 2024-04-01 18:27
Duplicate of #860

**Closed by joshtrichards** 2024-04-01 18:27 UTC
