### ISSUE TITLE
training error.  Not quite sure what im doing.

### ISSUE THREAD

**Issue by psyciknz** [nextcloud/suspicious_login#616] opened 2022-03-04 07:50 UTC
I was playing in nextcloud trying to get it to resolve client ips properly.  But in doing so looked in the logs and saw some errors about suspicion logins.

so I started digging into suspicion login app.

I then jumped into my container to run the train command.  But that generates the following error.   I couldn’t find anything pertaining to the error.

Any pointers I can look up?
Using ipv4 strategy
An unhandled exception has been thrown:
Error: Minimum value must be less than or equal to the maximum value in /config/www/nextcloud/apps/suspicious_login/lib/Service/NegativeSampleGenerator.php:74
Stack trace:
#0 /config/www/nextcloud/apps/suspicious_login/lib/Service/NegativeSampleGenerator.php(74): random_int()
#1 /config/www/nextcloud/apps/suspicious_login/lib/Service/NegativeSampleGenerator.php(114): OCA\SuspiciousLogin\Service\NegativeSampleGenerator->generateFromRealData()
#2 [internal function]: OCA\SuspiciousLogin\Service\NegativeSampleGenerator->OCA\SuspiciousLogin\Service\{closure}()
#3 /config/www/nextcloud/apps/suspicious_login/lib/Service/NegativeSampleGenerator.php(115): array_map()
#4 /config/www/nextcloud/apps/suspicious_login/lib/Service/DataLoader.php(123): OCA\SuspiciousLogin\Service\NegativeSampleGenerator->generateShuffledFromPositiveSamples()
#5 /config/www/nextcloud/apps/suspicious_login/lib/Command/Train.php(174): OCA\SuspiciousLogin\Service\DataLoader->generateRandomShuffledData()
#6 /config/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\SuspiciousLogin\Command\Train->execute()
#7 /config/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#8 /config/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#9 /config/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#10 /config/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#11 /config/www/nextcloud/console.php(100): OC\Console\Application->run()
#12 /config/www/nextcloud/occ(11): require_once('/config/www/nex...')

**Comment by eibex** [comment] 2022-03-27 00:09
#492

**Comment by joshtrichards** [comment] 2024-05-03 21:14
Duplicate of #745 
Fixed in #810

**Closed by joshtrichards** 2024-05-03 21:14 UTC
Labels: bug, 0. to triage
